[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/meeting"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/meeting/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cookie-policy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/messages/*"
  to = "/index.html"
  status = 200

